html_sheets/Vaetchanan/365.html: (<type 'exceptions.IndexError'>, IndexError('list index out of range',))
Traceback (most recent call last):
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 1106, in bs4_reader
    sheet.parse_as_text()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 204, in parse_as_text
    section.add_segments(section.soupObj)
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 243, in add_segments
    self.classify_segments(soup_segments) #self.segment_objects += self.classify_segments(soup_segments)
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 310, in classify_segments
    sheet_segment = self.classify(segment, i, soup_segments)
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 346, in classify
    current_source = [x for x in self.segment_objects if (isinstance(x, Source) and x.current)][-1]
IndexError: list index out of range


html_sheets/Vaetchanan/196.html: (<class 'sefaria.system.exceptions.BookNameError'>, BookNameError(u"No book named 'Vaetchanan'.",))
Traceback (most recent call last):
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 1107, in bs4_reader
    sheet.create_sheetsources_from_objsource()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 78, in create_sheetsources_from_objsource
    if not success and segment.ref and parser.source_is_tanakh(segment.ref) and parser.haftarah_mode:
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 886, in source_is_tanakh
    i = library.get_index(book_name)
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Project/sefaria/model/text.py", line 4175, in get_index
    raise BookNameError(u"No book named '{}'.".format(bookname))
BookNameError: No book named 'Vaetchanan'.


