html_sheets/Devarim/676.html: (<type 'exceptions.IOError'>, IOError(2, 'No such file or directory'))
Traceback (most recent call last):
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 1080, in bs4_reader
    content = BeautifulSoup(open("{}".format(html_sheet)), "lxml")
IOError: [Errno 2] No such file or directory: 'html_sheets/Devarim/676.html'


